### PR TITLE
Corrected Landing page

### PR DESCRIPTION
**Pull request by the-osiris**
Landing page was taking 80% of the screen, which should cover a total 100%. So corrected the landing page

### CODE REVIEW

**Comment by pvtg** [comment]
send the screenshot of the output

**Comment by the-osiris** [comment]
Screenshot (510)
Please check this

**Comment by pvtg** [comment]
Okay fine. But do not erase the full code and paste it again with your changes. Always make changes in the current code no matter how small your contribution is. it would be counted. It would become harder for the owner to analyze the code if you are changing the full code. I hope you can understand.

**Comment by the-osiris** [comment]
Yeah sure! I'm sorry for that

**Pull request merged**
